### ISSUE TITLE
Publish 1.9 on Maven Central

### ISSUE THREAD

**Issue by mikaelhg** [iamtakingiteasy/mouse#1]
Hi, please publish Mouse 1.9 on Maven Central. Thanks!

**Comment by iamtakingiteasy** [comment]
Done, version 1.9.1 should be synced with maven central soon.

**Comment by iamtakingiteasy** [comment]
BTW, try considering [parboiled](https://github.com/sirthias/parboiled) ; it may be a nice PEG-style alternative to build-time code generation.

**Comment by mikaelhg** [comment]
parboiled is otherwise nice, but the last time I looked, it has additional runtime dependencies, which are fine in an application project, but the last resort in a library project.
